### ISSUE TITLE
merge loophole and refactor?!?

### ISSUE THREAD

**Issue by jedie** [rsc-dev/A360#2]
I would like to bring this project in a useable state... Maybe it makes sence to merge the loophole project, because is it useable for other cases then A360 ?!?

It this project alive or should i fork and "make my own thing" ?!?

**Comment by rsc-dev** [comment]
Indeed, Those two projects should be merged, or A360 should be renamed.
It was first created for one "client" to help in medical research, but it is mature enough now.

I am more than happy of you want to help in merging A360 to loophole. 
I would encourage you to use those repositories, as they depend on reverse engineering protocol buffers. I will commit changes whenever Polar changes PB. Both projects are alive.

**Comment by jedie** [comment]
Then lets try to find a new project name and put all stuff together ;)

Whats about:

* PyFitnessTracker
* PyFitnessAnalyzer
* PyFitnessStatistics

I would like to create a real python package, so it can be uploaded to PyPi ;)

I don't know: Make it sence to leas "A360" and "loophole" as two project?!? Or are they not useable alone?!?

EDIT: btw my far destination it to merge the A360 tracker data with the .gpx files from https://github.com/khertan/ForRunners ;)
